name: Bender Catalog

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    name: Build and publish docker image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log in to Docker
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build fastapi and cronjob images
        run: |
          docker build -t ghcr.io/cis1880/hw4-jhawkman/unit4-fastapi:${{ github.sha }} ./web
          docker build -t ghcr.io/cis1880/hw4-jhawkman/unit4-cronjob:${{ github.sha }} ./cronjob
      - name: Push fastapi and cronjob images
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          cd ./web
          docker push ghcr.io/cis1880/hw4-jhawkman/unit4-cronjob:${{ github.sha }}
          cd ../cronjob
          docker push ghcr.io/cis1880/hw4-jhawkman/unit4-fastapi:${{ github.sha }}
  deploy:
    name: Deploy latest version of code
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up kubeconfig
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config
          chmod 600 ~/.kube/config
      - name: Add helm repository
        run: helm repo add cis188helm https://helm.cis188.org
      - name: Install helm chart
        run: |
          helm upgrade --install jhawkman-chart cis188helm/bender-catalog -f installation-values.yaml \
            --set web.tag=${{ github.sha }} --set cronjob.tag=${{ github.sha }}
